Radiology order basket
palladiumkenya/esm-radiology-app pull request #80
Opened 2024-07-02 13:27 UTC by charity553

## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Summary

## Screenshots

## Related Issue

https://openmrs.atlassian.net/browse/O3-3528

## Other

2024-07-13 12:23 UTC, donaldkibet approved these changes

2024-07-13 12:24 UTC, donaldkibet requested changes

2024-07-13 12:24 UTC, donaldkibet commented on src/form/radiology-orders/radiology-order-basket-panel/radiology-order-basket-panel.scss
> +  border-left: 4px solid #18cd69;
```suggestion
  border-left: 4px solid colors.$color-o1;
```
We should use carbon color tokens

2024-07-15 05:57 UTC, ojwanganto commented
@charity553 - please help address the review comments

2024-07-22 04:44 UTC, donaldkibet commented
@charity553 please fix the conflict to move this forward

2024-07-22 09:36 UTC, closed without merging

2024-07-22 10:04 UTC, donaldkibet commented
@charity553 please push the same branch, will trying to resolve the conficts i unfortunately overwrote you changes. Thanks