(feat) added radiology  price display on the basket
palladiumkenya/esm-radiology-app pull request #84
Opened 2024-07-12 22:25 UTC by its-kios09

## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Summary

-  added ability to show radiology prices on the order basket

## Screenshots

![radio](https://github.com/user-attachments/assets/42e415f1-c80f-46f5-9e53-6b17859c406e)

## Related Issue

## Other

2024-07-13 12:22 UTC, donaldkibet requested changes

2024-07-13 12:22 UTC, donaldkibet commented on src/form/radiology-orders/add-radiology-order/radiology-order-form.component.tsx
> +            name="top-of-lab-order-form-slot"
```suggestion
            name="top-of-imaging-order-form-slot"
```

We might also want to change this repo to `esm-imaging-app`

2024-07-15 22:04 UTC, its-kios09 commented on src/form/radiology-orders/add-radiology-order/radiology-order-form.component.tsx
> +            name="top-of-lab-order-form-slot"
so, what do you advise?

2024-07-16 06:18 UTC, ojwanganto commented on src/form/radiology-orders/add-radiology-order/radiology-order-form.component.tsx
> +            name="top-of-lab-order-form-slot"
renaming the app to imaging

2024-07-16 08:54 UTC, its-kios09 commented on src/form/radiology-orders/add-radiology-order/radiology-order-form.component.tsx
> +            name="top-of-lab-order-form-slot"
Okay, how about creating the slot from esm-billing-app

2024-07-17 13:12 UTC, its-kios09 commented on src/form/radiology-orders/add-radiology-order/radiology-order-form.component.tsx
> +            name="top-of-lab-order-form-slot"
> We might also want to change this repo to `esm-imaging-app`

Sorted

2024-07-17 21:11 UTC, ojwanganto commented
Tagging @makombe. Thanks, @its-kios09

2024-07-18 10:17 UTC, makombe approved these changes
Thanks @its-kios09. The ask to rename esm to imaging is still pending. I think that one you can address in a followup PR.

2024-07-19 05:17 UTC, merged