grouped radiology orders by patient
palladiumkenya/esm-radiology-app pull request #88
Opened 2024-07-27 12:02 UTC by FelixKiprotich350

## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Summary
in this PR i have improved the radiology module by grouping the orders by patient, and using an accordion list all orders alongside their actions.
Created a Grouping component reused across all the tabs.

## Screenshots
[screen-capture.webm](https://github.com/user-attachments/assets/bb6f4769-8f3c-42ef-8e46-45fe25c72f0b)

## Related Issue

## Other

2024-07-29 03:27 UTC, donaldkibet requested changes
Thanks @FelixKiprotich350 for this work. cc @ojwanganto looking at these designs should we align our work to this pattern for clinical management works e.g procedures, imaging, labs and billing [see](https://app.zeplin.io/project/6650717a9275db731847fb32/screen/66507e978b83a56175f3eaaa)

2024-07-29 03:27 UTC, donaldkibet commented on src/radiology-tabs/common/listOrderDetails.component.tsx
> +            </div>
Since we are repeating this logic it would be better to extract it to a component e.g

```tsx
export const OrderDetail: React.FC<{ label: string; value: string }> = ({ label, value }) => {
  <div>
    <p className={styles.bodyLong01}>
      <span className={styles.label01}>{label}</span>
      {' : '}
      <span className={styles.displayValue}>{value}</span>
    </p>
  </div>;
};
```

2024-07-29 03:27 UTC, donaldkibet commented on src/radiology-tabs/common/listOrderDetails.scss
> +@import "../../../node_modules/@openmrs/esm-styleguide/src/vars";
```suggestion
@use '@carbon/layout';
@use '@carbon/colors';
@use '@openmrs/esm-styleguide/src/vars' as *;
```

2024-07-29 03:27 UTC, donaldkibet commented on src/radiology-tabs/common/listOrderDetails.scss
> +  margin-bottom: 1rem !important;
```suggestion
  margin-bottom: 1rem !important;
```
if possible using `!important` should be the last options

2024-07-29 03:27 UTC, donaldkibet commented on src/radiology-tabs/common/listOrderDetails.scss
> +    color: #525252;
for both width and height lets use carbon token e.g `layout.$spacing-05` and `colors.$white-01`

2024-07-29 03:27 UTC, donaldkibet commented on src/radiology-tabs/common/radiologyProps.resource.ts
> +  orders: Result[];
for Arrray use `Array<T>` syntax

2024-07-29 05:16 UTC, FelixKiprotich350 commented on src/hooks/useSearchGroupedResults.ts
> +  data: GroupedOrders[],
okay i have changed that slightly to Array<GroupedOrders>

2024-07-29 06:34 UTC, FelixKiprotich350 commented on src/radiology-tabs/common/groupedOrdersTable.component.tsx
> +  const pageSizes = [10, 20, 30, 40, 50];
@donaldkibet  i am done with your comments but this seem unclear to me. any help on implementing this **usePaginationInfo**, the parameters are kinda confusing to me and cant find a similar implementation. Thanks

2024-07-29 06:50 UTC, FelixKiprotich350 commented on src/radiology-tabs/common/listOrderDetails.component.tsx
> +        });
@ thanks for your review i have effected the changes

2024-07-29 07:03 UTC, FelixKiprotich350 commented
@donaldkibet , @makombe  and @ojwanganto  Your suggestions are effected you can review

2024-07-29 08:10 UTC, ojwanganto commented
@FelixKiprotich350 - please remember to update the attached video/screenshots

2024-07-29 08:21 UTC, FelixKiprotich350 commented
@ojwanganto latest screen record of the interface updated on the PR

2024-07-29 08:37 UTC, ojwanganto commented
Thanks so much

2024-07-29 09:11 UTC, donaldkibet approved these changes

2024-07-30 06:18 UTC, makombe approved these changes
Thanks @FelixKiprotich350

2024-07-30 11:07 UTC, ojwanganto commented
Can we have this in?

2024-07-30 11:34 UTC, FelixKiprotich350 commented
Am working on the updates

On Tue, Jul 30, 2024, 2:07 PM ojwanganto ***@***.***> wrote:

> Can we have this in?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/palladiumkenya/esm-radiology-app/pull/88#issuecomment-2258088355>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARGPKMEAZGCID73NUGURVODZO5XXNAVCNFSM6AAAAABLR2HOOOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENJYGA4DQMZVGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-07-30 12:01 UTC, donaldkibet commented
@FelixKiprotich350 merge this in once you are done with the updates

2024-07-30 12:06 UTC, FelixKiprotich350 commented
Ok, I will do it.

On Tue, Jul 30, 2024, 3:02 PM Donald Kibet ***@***.***> wrote:

> @FelixKiprotich350 <https://github.com/FelixKiprotich350> merge this in
> once you are done with the updates
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/palladiumkenya/esm-radiology-app/pull/88#issuecomment-2258182099>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARGPKMEKMBBY4AIAU72WT3DZO56EHAVCNFSM6AAAAABLR2HOOOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENJYGE4DEMBZHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-07-30 18:00 UTC, FelixKiprotich350 commented
hello @donaldkibet am realizing that this PR is on radiology yet i was responding in the context of procedure module, so i think this is good to go and you can merge, if in case ill have to make any addition ill just open another PR

2024-07-30 20:04 UTC, merged

2024-07-30 20:04 UTC, ojwanganto commented
Thanks, @FelixKiprotich350